version: '3.8'

services:
  backend:
    build: ./job_application_tracker # Point this to your actual Django folder name
    ports:
      - "8000:8000"
    volumes:
      - ./job_application_tracker:/app

  frontend:
    build: ./react-app
    ports:
      - "3000:3000"
    volumes:
      - ./react-app/src:/app/src
    depends_on:
      - backend