# Generated by Django 6.0.1 on 2026-06-05 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_applied', models.BooleanField(default=False)),
                ('is_no_response', models.BooleanField(default=True)),
                ('is_rejected', models.BooleanField(default=False)),
                ('is_accepted', models.BooleanField(default=False)),
                ('in_interview_process', models.BooleanField(default=False)),
                ('on_hold', models.BooleanField(default=True)),
                ('is_remote', models.BooleanField(default=False)),
                ('is_hybrid', models.BooleanField(default=False)),
                ('is_office', models.BooleanField(default=True)),
                ('day_work_duration', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('apply_link', models.URLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
