# Generated by Django 6.0.1 on 2026-06-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='notes',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
